name: Frontend CI (Angular)

on:
  push:
    branches:
      - '**'
jobs:
  lint-test-build:
    name: Lint, Test & Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install Frontend Dependencies
        run: npm install

        #      - name: Run Linters
        # run: npm run lint # Make sure you have a lint script in package.json

      - name: Run Unit Tests (CI)
        run: npm run test:ci

      - name: Build Angular App (Production)
        run: npm run build -- --configuration production

  e2e-tests:
    name: End-to-End Tests (Cypress)
    runs-on: ubuntu-latest
    needs: lint-test-build

    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v4

      - name: Checkout Backend Repo
        uses: actions/checkout@v4
        with:
          repository: arthures11/music-store-backend
          path: ./music-store-backend

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Backend Dependencies
        working-directory: ./music-store-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install Frontend Dependencies
        run: npm install

      - name: Run E2E tests
        run: |
          echo "Starting backend server..."
          cd ./music-store-backend
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          BACKEND_PID=$!
          echo "Backend server started with PID $BACKEND_PID"
          cd ..
          
          echo "Running frontend E2E command..."
          npm run ci:e2e
          
          echo "Stopping backend server..."
          kill $BACKEND_PID
